### ISSUE TITLE
Préambule organisation

### ISSUE THREAD

**Issue by GuyliannEngels** [BioDataScience-Course/sdd-umons2#1]
Je pense que la structure du préambule peut suivre la structure proposé dans le premier ouvrage [science des données biologiques](http://biodatascience-course.sciviews.org/sdd-umons/)

- [x] Preambule

- [ ] Vue générale du cours

- [x] Matériel pédagogique

- [ ] Evaluation

Je me lance dans le préambule général

**Comment by phgrosjean** [comment]
Hé Guyliann,

C’est déjà fait (je lis ton mail seulement à l'instant)!
Il reste à renommer les différents modules (et bien sûr à modifier leur contenu)
A+,

Philippe
